name: Extended Checks

on:
  push:
    branches:
      - 'fix/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'fix/**'
      - 'feature/**'
env:
  DOTNET_VERSION: '6.0.101' # The .NET SDK version to use
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
      # sets up .NET Core SDK 6
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.101'
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
